#!/usr/bin/env python3
"""Generate the Pyquist landing page from the pinned submodule.

Stitches pyquist/README.md and pyquist/examples/HelloPyquist.ipynb into
content/pyquist/Overview.md, written as a MyST markdown notebook: the
README's Quick example section is replaced by the notebook tour, so the
code executes at build time and runs live in the browser. Run via
`make pyquist` (part of `make split`).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import nbformat

REPO = Path(__file__).resolve().parent.parent
README_SRC = REPO / "pyquist" / "README.md"
NOTEBOOK_SRC = REPO / "pyquist" / "examples" / "HelloPyquist.ipynb"
DEST = REPO / "content" / "pyquist" / "Overview.md"
STALE_FRAGMENT = REPO / "content" / "pyquist" / "_pyquist_readme.md"

GITHUB_EXAMPLES = "https://github.com/gclef-cmu/pyquist/blob/main/examples/"
COLAB_URL = (
    "https://colab.research.google.com/github/gclef-cmu/pyquist"
    "/blob/main/examples/HelloPyquist.ipynb"
)

from split_chapters import FENCE_RE, split_body  # noqa: E402

# file_format: mystnb is what myst-nb keys on to read the .md as a notebook.
HEADER = """\
---
file_format: mystnb
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
---

% GENERATED by tools/gen_pyquist_page.py (make pyquist); do not edit.
% Stitched from pyquist/README.md + pyquist/examples/HelloPyquist.ipynb.
"""

RUN_NOTE = (
    "Run any cell below right here in your browser with its Run button. "
    f"You can also open the original notebook in [Colab]({COLAB_URL})."
)

NUMBERED_H2_RE = re.compile(r"^## (\d+)\. ")


def rewrite_links(text: str) -> str:
    """Same rewrite the old sync-pyquist-readme sed did."""
    return text.replace("](examples/", "](" + GITHUB_EXAMPLES)


def squeeze_blanks(text: str) -> str:
    """Collapse blank-line runs left by dropped lines. Markdown only."""
    return re.sub(r"\n{3,}", "\n\n", text)


HEADING_LINE_RE = re.compile(r"^(#{1,5}) ")


def demote_headings_md(text: str) -> str:
    """Push headings one level down (## -> ###), skipping fenced code.

    The tour cells nest under the page's `## Hello, pyquist!` section, so
    their headings drop a level; a stray H1 in a tour cell would break the
    single-title structure and fails loudly.
    """
    out = []
    fence = None
    for line in text.splitlines():
        if fence is None:
            fm = FENCE_RE.match(line)
            if fm:
                fence = fm.group(1)
            elif line.startswith("# "):
                sys.exit(
                    "ERROR: HelloPyquist.ipynb grew an H1 inside the tour "
                    f"({line.strip()!r}); the page must keep a single title."
                )
            elif HEADING_LINE_RE.match(line):
                line = "#" + line
        else:
            stripped = line.strip()
            if stripped and set(stripped) == {fence[0]} and len(stripped) >= len(fence):
                fence = None
        out.append(line)
    return "\n".join(out)


def readme_parts() -> tuple[str, dict[str, str]]:
    body = README_SRC.read_text(encoding="utf-8").replace("\r\n", "\n")
    intro_lines, sections = split_body(body)
    parts = {title: "".join(lines) for title, lines, _targets in sections}
    for needed in ("Quick example", "Installation", "Acknowledgements"):
        if needed not in parts:
            sys.exit(
                f"ERROR: pyquist README lost its '## {needed}' section; "
                "update tools/gen_pyquist_page.py for the new shape."
            )
    # The Colab badge is redundant here: the page itself is runnable.
    intro = "".join(
        line for line in intro_lines if "colab.research.google.com" not in line
    )
    return squeeze_blanks(intro), parts


def code_cell(source: str) -> str:
    source = source.rstrip("\n")
    longest = max((len(m.group(0)) for m in re.finditer(r"`+", source)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}{{code-cell}} ipython3\n{source}\n{fence}"


def setup_cell(bootstrap_src: str) -> str:
    """Imports-only replacement for the notebook's Colab bootstrap cell.

    Keeps top-level import lines; the indented `!apt` / `!pip` Colab branch
    must never reach the page (the `!pip install --upgrade pyquist` would
    clobber the book's own wheel in the browser kernel).
    """
    imports = [
        line
        for line in bootstrap_src.splitlines()
        if re.match(r"^(import|from) ", line)
    ]
    source = "# Setup: imports used by every cell below. Run this cell first.\n"
    source += "\n".join(imports)
    if "import pyquist" not in source:
        sys.exit(
            "ERROR: HelloPyquist setup cell no longer imports pyquist; "
            "update tools/gen_pyquist_page.py."
        )
    return code_cell(source)


def tour_blocks(nb) -> list[str]:
    cells = nb.cells
    if not (cells and cells[0].cell_type == "markdown" and cells[0].source.startswith("# ")):
        sys.exit("ERROR: HelloPyquist.ipynb no longer opens with a markdown H1 cell.")
    if len(cells) < 3 or cells[1].cell_type != "code":
        sys.exit("ERROR: HelloPyquist.ipynb no longer has its setup code cell second.")

    # Keep the tour's own title as a section under the page title; the
    # numbered sections nest one level below it. Drop the Shift+Enter note
    # (this page runs cells with a Run button).
    head = []
    for line in cells[0].source.splitlines():
        if line.startswith("# "):
            head.append("#" + line)
        elif "Shift+Enter" not in line:
            head.append(line)
    blurb = squeeze_blanks("\n".join(head)).strip("\n")

    blocks = [blurb + "\n\n" + RUN_NOTE, setup_cell(cells[1].source)]

    counter = 0
    for cell in cells[2:]:
        if cell.cell_type == "code":
            blocks.append(code_cell(cell.source))
            continue
        src = cell.source
        # Skip the What's next? outro; the book doesn't link to pyquist.org.
        if src.lstrip().startswith("## What's next?"):
            continue
        # Renumber sections; upstream numbering has gaps and repeats.
        m = NUMBERED_H2_RE.match(src)
        if m:
            counter += 1
            src = f"## {counter}. " + src[m.end():]
        blocks.append(demote_headings_md(rewrite_links(src)))
    return blocks


def main() -> None:
    for path in (README_SRC, NOTEBOOK_SRC):
        if not path.exists():
            sys.exit(
                f"ERROR: {path.relative_to(REPO)} not found — is the submodule "
                "initialized?\n  run: git submodule update --init pyquist"
            )

    intro, parts = readme_parts()
    nb = nbformat.read(NOTEBOOK_SRC, as_version=4)

    blocks = [HEADER, rewrite_links(intro)]
    blocks += tour_blocks(nb)
    blocks.append(rewrite_links("## Installation\n" + parts["Installation"]))
    blocks.append(rewrite_links("## Acknowledgements\n" + parts["Acknowledgements"]))

    doc = "\n\n".join(block.strip("\n") for block in blocks) + "\n"

    DEST.parent.mkdir(parents=True, exist_ok=True)
    if DEST.exists() and DEST.read_text(encoding="utf-8") == doc:
        print(f"unchanged: {DEST.relative_to(REPO)}")
    else:
        DEST.write_text(doc, encoding="utf-8")
        print(f"wrote {DEST.relative_to(REPO)}")

    if STALE_FRAGMENT.exists():
        STALE_FRAGMENT.unlink()
        print(f"removed stale {STALE_FRAGMENT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
